#---------------------------------------
# Load libraries and prepare data
#---------------------------------------
source("data_cleaning.R")
source("prefs_to_choices.R")
#---------------------------------------



#---------------------------------------
# Define the profiles of choice
#---------------------------------------
# Define the choice/pref profiles for Spec, Low, High
# the choices in the profiles are
# A1_A7_neg, A1_A4_neg, A4_A7_neg, A2_A3_neg,
# A1_A7_no, A1_A4_no, A4_A7_no, A2_A3_no,
# A1_A7_pos, A1_A4_pos, A4_A7_pos, A2_A3_pos
# 0 means that the fist alternative is preferred,
# 1 that the second alternative is preferred,
# NA means that there is indifference

profiles_spec <- NULL 
for(i in prefs_spectator){
  pref_string <- i
  binary_choices <- list(c(1, 7), c(1, 4), c(4, 7), c(2, 3))
  profiles_spec <- rbind(profiles_spec, evaluate_choices(pref_string, binary_choices))
} 
print(profiles_spec)

profiles_low <- NULL
for(i in prefs_low){
  pref_string <- i
  binary_choices <- list(c(1, 7), c(1, 4), c(4, 7), c(2, 3))
  profiles_low <- rbind(profiles_low, evaluate_choices(pref_string, binary_choices))
} 
print(profiles_low)

profiles_high <- NULL
for(i in prefs_high){
  pref_string <- i
  binary_choices <- list(c(1, 7), c(1, 4), c(4, 7), c(2, 3))
  profiles_high <- rbind(profiles_high, evaluate_choices(pref_string, binary_choices))
} 
print(profiles_high)

# Define the choice/pref profiles for Medium
# the choices in the profiles are
# A1_A7_neg, A2_A7_neg, A3_A7_neg, A2_A3_neg,
# A1_A7_no, A2_A7_no, A3_A7_no, A2_A3_no,
# A1_A7_pos, A2_A7_pos, A3_A7_pos, A2_A3_pos
# 0 means that the fist alternative is preferred,
# 1 that the second alternative is preferred,
# NA means that there is indifference

profiles_medium <- NULL
for(i in prefs_medium){
  pref_string <- i
  binary_choices <- list(c(1, 7), c(2, 7), c(3, 7), c(2, 3))
  profiles_medium <- rbind(profiles_medium, evaluate_choices(pref_string, binary_choices))
} 
print(profiles_medium)
#---------------------------------------



#---------------------------------------
# Define functions to calulate the components
# of the likelihood function
#---------------------------------------
# Function computing number Corrette, Sbagliate, e Indifferenti for each profile
evaluate_choice <- function(x, mat) {

  if (length(x) != ncol(mat)) {
    stop("Input vector must have length ", ncol(mat))
  }

  # For each row compute counts
  result <- t(apply(mat, 1, function(row) {

    na_count  <- sum(is.na(row))

    equal_count <- sum(row == x, na.rm = TRUE)

    diff_count  <- sum(row != x, na.rm = TRUE)

    c(equal = equal_count,
      different = diff_count,
      na = na_count)
  }))

  return(result)
}

#Calculate the prob of obtainig the data given a tremble for each profile
tremble_lik <- function(tremble, vec) {
  C <- vec[, , 1]
  S <- vec[, , 2]
  I <- vec[, , 3]
  (1 - tremble/2)^C * (tremble/2)^S * (0.5)^I
}

#Functions that computes the p that the choice is generated by a specific motive
#as conditional on the prob that the motive uses a profile
prob_profile_given_type_spec <- function(pmt, vec){
  a <- pmt[1:5] #5 par
  M <- cbind(
    c(1,   0,   0,   0,   0,   0,   0,   0), #Spec Self
    c(0,   0,   0,   0,   0,   0,   0,   1), #Spec Self_Mob
    c(0,   1,   0,   0,   0,   0,   0,   0), #Spec Self_Mer
	c(0,   0,a[1],a[2],a[3],a[4],a[5],   0), #Spec Self_Mob_Mer
	c(1,   0,   0,   0,   0,   0,   0,   0)  #Spec Rand
  )
  vec %*% M
}

prob_profile_given_type_low <- function(pmt, vec){
  a <- pmt[1:5] #5 par
  M <- cbind(
    c(0,   1,   0,   0,   0,   0,   0), #Low Self
	c(0,   1,   0,   0,   0,   0,   0), #Low Self_Mob
	c(0,   0,a[1],a[2],a[3],a[4],a[5]), #Low Self_Mer
	c(0,   0,a[1],a[2],a[3],a[4],a[5]), #Low Self_Mob_Mer
	c(1,   0,   0,   0,   0,   0,   0)  #Low Rand
  )
  vec %*% M
}

prob_profile_given_type_high <- function(pmt, vec){
  a <- pmt[1:5] #5 par
  b <- pmt[6:10] #5 par
  c <- pmt[11:35] #25 par
  M <- cbind(
    c(0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,   0,    0,    0,    0,    0,    0,   0,    0,    0,    0,    0,    0,   0,    0,    0,    0,    0,    0), #High Self
	c(0,   0,   0,   0,   0,   0,   0,b[1],   0,   0,   0,   0,   0,b[2],   0,   0,   0,   0,    0,b[3],    0,    0,    0,    0,    0,b[4],    0,    0,    0,    0,    0,b[5],    0,    0,    0,    0,    0), #High Self_Mob
	c(0,   0,a[1],a[2],a[3],a[4],a[5],   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,   0,    0,    0,    0,    0,    0,   0,    0,    0,    0,    0,    0,   0,    0,    0,    0,    0,    0), #High Self_Mer
	c(0,   0,   0,   0,   0,   0,   0,   0,c[1],c[2],c[3],c[4],c[5],   0,c[6],c[7],c[8],c[9],c[10],   0,c[11],c[12],c[13],c[14],c[15],   0,c[16],c[17],c[18],c[19],c[20],   0,c[21],c[22],c[23],c[24],c[25]), #High Self_Mob_Mer
	c(1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,   0,    0,    0,    0,    0,    0,   0,    0,    0,    0,    0,    0,   0,    0,    0,    0,    0,    0)  #High Rand
  )
  vec %*% M
}

prob_profile_given_type_medium <- function(pmt, vec){
  a <- pmt[1:4] #4 par
  b <- pmt[5:6] #2 par
  c <- pmt[7:18] #12 par
  M <- cbind(
    c(0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,    0,    0), #Medium Self
	c(0,   0,   0,   0,   0,   0,b[1],   0,   0,   0,   0,   0,   0,   0,b[2],   0,   0,    0,    0,    0), #Medium Self_Mob
	c(0,   0,a[1],a[2],a[3],a[4],   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,    0,    0), #Medium Self_Mer
	c(0,   0,   0,   0,   0,   0,   0,c[1],c[2],c[3],c[4],c[5],c[6],c[7],   0,c[8],c[9],c[10],c[11],c[12]), #Medium Self_Mob_Mer
	c(1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,    0,    0,    0)  #Medium Rand
  )
  vec %*% M
}

# Define utility fuction for reparametrization of probs
softmax <- function(x) {
  z <- x - max(x)
  e <- exp(z)
  e / sum(e)
}

# Define utility function for computing log(sum(pi*marg_lik)) avoiding overflow
logsumexp <- function(x) {
  m <- max(x)
  m + log(sum(exp(x - m)))
}


negloglik <- function(par, C_spec, C_high, C_medium, C_low) {
  pi <- softmax(par[1:5])
  tremble_spec <- par[6]
  tremble_high <- par[7]
  tremble_medium <- par[8]
  tremble_low <- par[9]

  pmt_spec <- softmax(par[10:14]) #5 par
  pmt_low <- softmax(par[15:19]) #5 par
  pmt_medium <- c(softmax(par[20:23]), softmax(par[24:25]), softmax(par[26:37])) #18 par
  pmt_high <- c(softmax(par[38:42]), softmax(par[43:47]), softmax(par[48:72])) # 35 par

  #Compute the individual lik conditional on the motive
  m_comp_spec <- prob_profile_given_type_spec(pmt_spec,tremble_lik(tremble_spec, C_spec))
  m_comp_low <- prob_profile_given_type_low(pmt_low,tremble_lik(tremble_low, C_low))
  m_comp_medium <- prob_profile_given_type_medium(pmt_medium,tremble_lik(tremble_medium, C_medium))
  m_comp_high <- prob_profile_given_type_high(pmt_high,tremble_lik(tremble_high, C_high))

  log_terms_spec <- sweep(log(m_comp_spec), 2, log(pi), "+")
  log_terms_low <- sweep(log(m_comp_low), 2, log(pi), "+")
  log_terms_medium <- sweep(log(m_comp_medium), 2, log(pi), "+")
  log_terms_high <- sweep(log(m_comp_high), 2, log(pi), "+")

  li_spec <- apply(log_terms_spec, 1, logsumexp)
  li_low <- apply(log_terms_low, 1, logsumexp)
  li_medium <- apply(log_terms_medium, 1, logsumexp)
  li_high <- apply(log_terms_high, 1, logsumexp)

  ll <- sum(li_spec) + sum(li_high) + sum(li_low)+ sum(li_medium)
  if (!is.finite(ll)) return(1e100)  # penalize invalid regions

  -ll
}
#---------------------------------------



#---------------------------------------
# Prepare the data for the ML estimation
# Calculate the number of correct, wrong, and Indiff
# choices given the profile
#---------------------------------------

# Prepare the data select only the 12 main choices for Spec, High and Low
summary_df <- df_long %>%
  filter(parent_status != "Medium") %>%
  filter(alternatives == "A1_A7" |  alternatives == "A1_A4" | alternatives == "A4_A7" | alternatives == "A2_A3") %>%
  mutate(
    seq_alt = interaction(alternatives, meritocracy, sep = "_"),
    seq_alt = factor(seq_alt, levels = c("A1_A7_negative", "A1_A4_negative", "A4_A7_negative","A2_A3_negative",
                                         "A1_A7_no", "A1_A4_no", "A4_A7_no","A2_A3_no",
                                         "A1_A7_positive", "A1_A4_positive", "A4_A7_positive","A2_A3_positive")),
    mob_ch =  case_when(
      alternatives == "A1_A4" & choice == "A4" ~ 1,
      alternatives == "A2_A3" & choice == "A3" ~ 1,
      choice == "A7" ~ 1,
      TRUE ~ 0
    )
  ) %>%
  arrange(parent_status, participant_code, seq_alt)

# Turn it into wide
summary_df <- summary_df %>%
  select(participant_code, seq_alt, parent_status, mob_ch) %>%
  mutate(seq_alt = as.integer(seq_alt)) %>%
  pivot_wider(
    names_from  = seq_alt,
    values_from = mob_ch,
    names_prefix = "ch"
  ) %>%
  # ensure the columns are exactly ch1..ch9 in order
  select(participant_code, parent_status, all_of(paste0("ch", 1:12)))

# Matrix of the choices of each participant (in row)
X <- summary_df %>%
  select(ch1:ch12) %>%
  as.matrix()

# Vettore 3D con n C, S, I per participant and profile
# Spectators
dati_stima_spec <- t(apply(X[1:48,], 1, evaluate_choice, mat = profiles_spec))
dati_stima_spec <- array(dati_stima_spec, c(48,nrow(profiles_spec),3)) #Prima dimesnione participant, seconda profile, terza C, S , I
id_spec <- summary_df$participant_code[1:48]
# High
dati_stima_high <- t(apply(X[49:96,], 1, evaluate_choice, mat = profiles_high))
dati_stima_high <- array(dati_stima_high, c(48,nrow(profiles_high),3)) #Prima dimesnione participant, seconda profile, terza C, S , I
id_high <- summary_df$participant_code[49:96]
# Low
dati_stima_low <- t(apply(X[97:144,], 1, evaluate_choice, mat = profiles_low))
dati_stima_low <- array(dati_stima_low, c(48,nrow(profiles_low),3)) #Prima dimesnione participant, seconda profile, terza C, S , I
id_low <- summary_df$participant_code[97:144]

# Prepare the data select only the 12 main choices for Medium
summary_df <- df_long %>%
  filter(parent_status == "Medium") %>%
  filter(alternatives == "A1_A7" |  alternatives == "A2_A7" | alternatives == "A3_A7" | alternatives == "A2_A3") %>%
  mutate(
    seq_alt = interaction(alternatives, meritocracy, sep = "_"),
    seq_alt = factor(seq_alt, levels = c("A1_A7_negative", "A2_A7_negative", "A3_A7_negative", "A2_A3_negative",
                                         "A1_A7_no", "A2_A7_no", "A3_A7_no", "A2_A3_no",
                                         "A1_A7_positive", "A2_A7_positive", "A3_A7_positive", "A2_A3_positive")),
    mob_ch =  case_when(
      alternatives == "A2_A3" & choice == "A3" ~ 1,
      choice == "A7" ~ 1,
      TRUE ~ 0
    )) %>%
  arrange(parent_status, participant_code, seq_alt)

# Turn it into wide
summary_df <- summary_df %>%
  select(participant_code, seq_alt, parent_status, mob_ch) %>%
  mutate(seq_alt = as.integer(seq_alt)) %>%
  pivot_wider(
    names_from  = seq_alt,
    values_from = mob_ch,
    names_prefix = "ch"
  ) %>%
  # ensure the columns are exactly ch1..ch9 in order
  select(participant_code, parent_status, all_of(paste0("ch", 1:12)))

# Matrix of the choices of each participant (in row)
X <- summary_df %>%
  select(ch1:ch12) %>%
  as.matrix()

# Vettore 3D con n C, S, I per participant and profile
# Medium
dati_stima_medium <- t(apply(X, 1, evaluate_choice, mat = profiles_medium))
dati_stima_medium <- array(dati_stima_medium, c(48,nrow(profiles_medium),3)) #Prima dimesnione participant, seconda profile, terza C, S , I
id_medium <- summary_df$participant_code
#---------------------------------------